env = DefaultEnvironment()

vpath = '#/third_party/openssl-1.0.2k'
str_vpath = str(Dir(vpath).abspath)

config_opts = '--prefix=' + str(Dir('#/build').abspath)

cmd = ('cd ' + str_vpath + ' & ' +
       'perl Configure debug-VC-WIN64A ' + config_opts + ' & ' +
       r'ms\do_win64a & nmake -f ms\nt.mak & nmake -f ms\nt.mak install')

libs = [str(File('#/build/lib/libeay32.lib')), str(File('#/build/lib/ssleay32.lib'))]
openssl_cfg = env.Command(libs, vpath, cmd)
