# -*- mode: python; -*-
import os
import subprocess
from distutils.dir_util import copy_tree
from shutil import copyfile

default = DefaultEnvironment()
env = default.Clone()

gtest_path = '#/third_party/googletest-release-1.8.0/googletest'
gmock_path = '#/third_party/googletest-release-1.8.0/googlemock'

gtest_dir = env.Install('#/build/include', gtest_path + '/include/gtest')
gmock_dir = env.Install('#/build/include', gmock_path + '/include/gmock')
gunit_h = env.Install('#/build/include/testing', 'gunit.h')
env.Depends(gunit_h, [gtest_dir, gmock_dir])


include = [
    gtest_path, gtest_path + '/include',
    gmock_path, gmock_path + '/include'
]

env.VariantDir(Dir('.').abspath + '/gtest', gtest_path + '/src')
env.VariantDir(Dir('.').abspath + '/gmock', gmock_path + '/src')

output_gmock = File('#/build/lib/gmock.lib')
output_gtest = File('#/build/lib/gtestd.lib')

def gtest_build(target, source, env):
    msbuild = [os.environ['MSBUILD'], 'gtest.sln']
    copy_tree(Dir('#/controller/lib/gunit/msvc15/gtest').abspath, Dir(gtest_path).abspath + r'\msvc')
    subprocess.call(msbuild, cwd=os.path.join(Dir(gtest_path).abspath,'msvc'))
    fromfile = os.path.join(Dir(gtest_path).abspath , r'msvc\x64\Debug\gtest.lib')
    copyfile(fromfile, output_gtest.abspath)

env.Command(output_gtest, Dir(gtest_path), gtest_build)

def gmock_build(target, source, env):
    msbuild = [os.environ['MSBUILD'], 'gmock.sln']
    copy_tree(Dir('#/controller/lib/gunit/msvc15/gmock').abspath, Dir(gmock_path).abspath + r'\msvc\2015')
    subprocess.call(msbuild, cwd=os.path.join(Dir(gmock_path).abspath, r'/msvc/2015'))
    fromfile = os.path.join(Dir(gmock_path).abspath, r'msvc\2015\Debug\gmock.lib')
    copyfile(fromfile, output_gmock.abspath)

env.Command(output_gmock, Dir(gmock_path), gmock_build)
