# -*- mode: python; -*-

import os
import re
import subprocess
import sys
import glob
from distutils.dir_util import copy_tree
from shutil import copy

vpath = '#/third_party/tbb2017_20160916oss'

env = DefaultEnvironment()

if env['TARGET_ARCH'] == 'x86':
   arch = 'ia32'
else:
   arch = 'intel64'

vcversion = 'vc14'
bindir = r'\build\windows_' + arch + '_cl_' + vcversion +'_' + env['TARGET_CONFIG'] #debug is default for now
abs_vpath = Dir(vpath).abspath

def build_tbb_for_windows(target,source,env):
    srcdir = Dir(vpath +'/include/tbb').abspath
    destdir = Dir('#/build/include/tbb').abspath
    copy_tree(srcdir, destdir)
    BUILD_ENV = {'PATH': env['ENV']['PATH'],
              'tbb_build_dir': Dir('.').abspath,'tbb_root': Dir(vpath).abspath,'runtime':'vc14'
            }
    cwd = os.getcwd()
    os.chdir(abs_vpath)
    subprocess.call("make tbb", shell=True)
    files = glob.iglob(os.path.join(abs_vpath, bindir, "*.dll"))
    for file in files:
        if os.path.isfile(file):
            copy(file, env.Dir(env['TOP_BIN']).abspath)
    files = glob.iglob(os.path.join(abs_vpath, bindir, "*.lib"))
    for file in files:
        if os.path.isfile(file):
            copy(file, env.Dir(env['TOP_LIB']).abspath)
    os.chdir(cwd)

#shutil.copytree()

#os.symcopy(Dir(vpath + '/include/tbb').abspath, Dir('#/build/include/tbb').abspath)
env.Command(['#build/lib/tbb_debug.lib', '#/build/include/tbb/mutex.h'], Dir(vpath), build_tbb_for_windows)

