import os
import subprocess
from shutil import copyfile

vpath = '#/windows/windowsstubs'

env = DefaultEnvironment()

abs_vpath = Dir(vpath).abspath
windowsstubs_lib = '#build/lib/windowsstubs.lib'

def build_windowsstubs_lib(target, source, env):
   msbuildcmd = [os.environ['MSBUILD'], 'WindowsStubs.sln', '/p:platform=x64', '/p:Configuration=Debug']
   subprocess.call(msbuildcmd, cwd = abs_vpath)
   copyfile(File('#/windows/windowsstubs/x64/debug/windowsstubs.lib').abspath, File(windowsstubs_lib).abspath)

sources = ['#windows/winutils.cc', '#windows/windowsstubs/windowsstubs/timeutils.cc', '#windows/windowsstubs/windowsstubs/agentconstants.cc', '#windows/windowsstubs/windowsstubs/wmi.cc' , '#windows/windowsstubs/windowsstubs/cpuinfo.cc']
env.Command(windowsstubs_lib, sources , build_windowsstubs_lib)
env.Alias('windowsstubs', windowsstubs_lib)
