env = DefaultEnvironment().Clone()

env.AppendUnique(CCFLAGS=['/DUNICODE', '/D_UNICODE']) #both are needed by the compiler

vpath = '#windows/src'
env.VariantDir('#/' + Dir('.').path + '/src', vpath, duplicate=0)

files = Glob(vpath +'/*.cc') + [vpath + '/sys/ioctl.cc', vpath + '/sys/time.cc']
windowsstubs_lib = env.Library('windowsstubs', files)
env.Install('#/build/lib/', 'windowsstubs.lib')
env.Alias('windowsstubs', '#/build/lib/windowsstubs.lib')
